package demo.spring.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2015-03-12T11:17:10.288-04:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://service.spring.demo/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://service.spring.demo/", className = "demo.spring.service.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
